const ACTIONS = {
  SET_GLOBAL_INFO: 'SET_GLOBAL_INFO',
  SET_DELIVERY_DATE_INFO: 'SET_DELIVERY_DATE_INFO',
  SET_STORE_LIST: 'SET_STORE_LIST',
  SET_STORE_INFO: 'SET_STORE_INFO',
  UPDATE_REMIND: 'UPDATE_REMIND',
  RECOMMEND_BANNER_VISIBLE: 'RECOMMEND_BANNER_VISIBLE',
}

export default ACTIONS
