import '../../../globals.css'
import { useLocale } from 'next-intl'
import { headers, cookies } from 'next/headers'
import { isDevice } from '~/utils/device'

export const metadata = {
  title: 'Create Next App PdpLayout',
  description: 'Generated by create next app PdpLayout',
}

// export async function generateStaticParams() {
//   return i18n.locales.map((locale) => ({ lang: locale }))
// }

export default async function PdpLayout({ mobile, pc }) {
  const lang = useLocale()
  const headerList = headers()
  const isMobile = isDevice(headerList.get('user-agent'), 'h5')

  return (
    <html lang={lang}>
      <body>
        <div>PdpLayout</div>
        <main>{isMobile ? mobile : pc}</main>
      </body>
    </html>
  )
}
