import './globals.css'
import Sidebar from '~/components/layout/sidebar'
import { useLocale } from 'next-intl'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export async function generateStaticParams() {
//   return i18n.locales.map((locale) => ({ lang: locale }))
// }

export default async function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: string } }) {
  const lang = useLocale()

  return (
    <html lang={lang}>
      <body>
        <main>{children}</main>
        <Sidebar />
      </body>
    </html>
  )
}
