import '../globals.css'
import { useLocale } from 'next-intl'

export const metadata = {
  title: 'Create Next App WeeeLayout',
  description: 'Generated by create next app WeeeLayout',
}

// export async function generateStaticParams() {
//   return i18n.locales.map((locale) => ({ lang: locale }))
// }

export default async function WeeeLayout({ children, params }: { children: React.ReactNode; params: { lang: string } }) {
  const lang = useLocale()

  return (
    <html lang={lang}>
      <body>
        <div>WeeeLayout</div>
        <main>{children}</main>
      </body>
    </html>
  )
}
